import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/service.dart';
import '../providers/service_provider.dart';
import 'service_details_screen.dart';

class Accueil extends StatefulWidget { const Accueil({super.key}); @override State<Accueil> createState() => _AccueilState(); }
class _AccueilState extends State<Accueil> {
 String _query=''; bool _showIssuesOnly=false;
 @override void initState(){super.initState(); WidgetsBinding.instance.addPostFrameCallback((_){final p=context.read<ServiceProvider>(); if(p.services.isEmpty&&!p.isLoading)p.fetchServices();});}
 @override Widget build(BuildContext context){final p=context.watch<ServiceProvider>(); final services=p.services; final operational=services.where((s)=>s.status==ServiceStatus.operational).length; final degraded=services.where((s)=>s.status==ServiceStatus.degraded).length; final down=services.where((s)=>s.status==ServiceStatus.down).length; final color=down>0?const Color(0xffdc3545):degraded>0?const Color(0xffff9800):const Color(0xff28a745); final filtered=services.where((s)=>s.name.toLowerCase().contains(_query.toLowerCase())&&(!_showIssuesOnly||s.status!=ServiceStatus.operational)); return Scaffold(backgroundColor:const Color(0xfff7f8fa),body:RefreshIndicator(onRefresh:p.fetchServices,child:ListView(padding:const EdgeInsets.fromLTRB(16,46,16,24),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('StatusDesk',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),IconButton(onPressed:p.isLoading?null:p.fetchServices,icon:p.isLoading?const CircularProgressIndicator():const Icon(Icons.refresh))]),const SizedBox(height:20),Card(color:color.withOpacity(.12),child:ListTile(leading:CircleAvatar(backgroundColor:color,child:Icon(down>0||degraded>0?Icons.priority_high:Icons.check,color:Colors.white)),title:Text(down>0?'Des services sont actuellement indisponibles.':degraded>0?'Certains services rencontrent des ralentissements.':'Tout fonctionne bien !'),subtitle:Text('Dernière synchro : ${p.lastSync??'En attente'}'))),const SizedBox(height:20),Row(children:[Expanded(child:_MetricCard(label:'Opérationnels',count:operational,color:const Color(0xff28a745),icon:Icons.check_circle)),const SizedBox(width:8),Expanded(child:_MetricCard(label:'Dégradé',count:degraded,color:const Color(0xffff9800),icon:Icons.warning_rounded)),const SizedBox(width:8),Expanded(child:_MetricCard(label:'Indisponible',count:down,color:const Color(0xffdc3545),icon:Icons.cancel))]),const SizedBox(height:28),const Text('Services',style:TextStyle(fontSize:23,fontWeight:FontWeight.bold)),const SizedBox(height:10),TextField(onChanged:(v)=>setState(()=>_query=v),decoration:InputDecoration(hintText:'Rechercher un service...',prefixIcon:const Icon(Icons.search),suffixIcon:IconButton(onPressed:()=>setState(()=>_showIssuesOnly=!_showIssuesOnly),icon:Icon(Icons.tune,color:_showIssuesOnly?color:Colors.grey)),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:BorderSide.none))),const SizedBox(height:12),if(p.isLoading&&services.isEmpty)const Center(child:CircularProgressIndicator()) else if(p.error!=null&&services.isEmpty)Text(p.error!) else ...filtered.map((s)=>_ServiceCard(service:s))])));}
}
class _MetricCard extends StatelessWidget{final String label;final int count;final Color color;final IconData icon;const _MetricCard({required this.label,required this.count,required this.color,required this.icon});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(vertical:14,horizontal:8),decoration:BoxDecoration(color:color.withOpacity(.1),borderRadius:BorderRadius.circular(13)),child:Column(children:[Icon(icon,color:color),Text('$count',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold,color:color)),Text(label,style:TextStyle(color:color))]));}
class _ServiceCard extends StatelessWidget{final Service service;const _ServiceCard({required this.service});@override Widget build(BuildContext context){final c=service.status==ServiceStatus.operational?const Color(0xff28a745):service.status==ServiceStatus.degraded?const Color(0xffff9800):const Color(0xffdc3545);return Card(child:ListTile(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>ServiceDetailScreen(service:service))),leading:CircleAvatar(backgroundColor:c.withOpacity(.14),child:Icon(Icons.check,color:c)),title:Text(service.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(service.status.name),trailing:Text('${service.responseTime} ms')));}}
