import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/service.dart';
import '../providers/service_provider.dart';

class ServiceDetailScreen extends StatelessWidget {
  final Service service;
  const ServiceDetailScreen({super.key, required this.service});
  Service _latest(BuildContext context) => context.read<ServiceProvider>().services.where((item) => item.url == service.url).firstOrNull ?? service;
  @override Widget build(BuildContext context) {
    context.watch<ServiceProvider>(); final current = _latest(context); final provider = context.read<ServiceProvider>(); final history = provider.historyFor(current.url); final color = _statusColor(current.status);
    return Scaffold(backgroundColor: const Color(0xfff8f9fa), appBar: AppBar(backgroundColor: const Color(0xfff8f9fa), elevation: 0, leading: IconButton(icon: const Icon(Icons.arrow_back), onPressed: () => Navigator.of(context).pop()), title: const Text('Détails du service', style: TextStyle(fontWeight: FontWeight.w600))), body: SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(16, 14, 16, 24), children: [CircleAvatar(radius: 38, backgroundColor: color, child: Icon(_statusIcon(current.status), color: Colors.white, size: 36)), const SizedBox(height: 14), Text(current.name, textAlign: TextAlign.center, style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold)), const SizedBox(height: 10), Center(child: Container(padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7), decoration: BoxDecoration(color: color.withOpacity(.14), borderRadius: BorderRadius.circular(24)), child: Text(_statusLabel(current.status), style: TextStyle(color: color, fontWeight: FontWeight.bold)))), const SizedBox(height: 24), _MetricsCard(service: current), const SizedBox(height: 16), _DescriptionCard(service: current), const SizedBox(height: 16), _HistoryCard(history: history, current: current), const SizedBox(height: 24), SizedBox(width: double.infinity, height: 52, child: ElevatedButton(onPressed: () => Navigator.of(context).pop(), style: ElevatedButton.styleFrom(backgroundColor: const Color(0xff2196f3), foregroundColor: Colors.white), child: const Text('Retour', style: TextStyle(fontWeight: FontWeight.bold))))])));
  }
  Color _statusColor(ServiceStatus s) => s == ServiceStatus.operational ? const Color(0xff28a745) : s == ServiceStatus.degraded ? const Color(0xffff9800) : const Color(0xffdc3545);
  IconData _statusIcon(ServiceStatus s) => s == ServiceStatus.operational ? Icons.check : s == ServiceStatus.degraded ? Icons.priority_high : Icons.close;
  String _statusLabel(ServiceStatus s) => s == ServiceStatus.operational ? 'Opérationnel' : s == ServiceStatus.degraded ? 'Dégradé' : 'Indisponible';
}

class _MetricsCard extends StatelessWidget { final Service service; const _MetricsCard({required this.service}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.symmetric(horizontal: 16), child: Column(children: [_MetricRow(icon: Icons.access_time, label: 'Temps de réponse', value: service.status == ServiceStatus.down ? '—' : '${service.responseTime} ms'), const Divider(height: 1), _MetricRow(icon: Icons.check_circle_outline, label: 'Disponibilité (uptime)', value: service.status == ServiceStatus.down ? 'Indisponible' : '99.98%'), const Divider(height: 1), _MetricRow(icon: Icons.calendar_today_outlined, label: 'Dernière vérification', value: _date(service.lastChecked)), const Divider(height: 1), _MetricRow(icon: Icons.link, label: 'Endpoint', value: service.url, multiline: true)]))); String _date(DateTime v) => '${v.day.toString().padLeft(2, '0')}/${v.month.toString().padLeft(2, '0')}/${v.year} - ${v.hour.toString().padLeft(2, '0')}:${v.minute.toString().padLeft(2, '0')}'; }
class _MetricRow extends StatelessWidget { final IconData icon; final String label; final String value; final bool multiline; const _MetricRow({required this.icon, required this.label, required this.value, this.multiline = false}); @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.symmetric(vertical: 16), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, color: const Color(0xff607d8b), size: 21), const SizedBox(width: 12), Expanded(child: Text(label, style: const TextStyle(color: Color(0xff5f6368)))), const SizedBox(width: 12), Flexible(child: Text(value, textAlign: TextAlign.right, maxLines: multiline ? 3 : 2, overflow: TextOverflow.ellipsis, style: const TextStyle(fontWeight: FontWeight.w600)))])); }
class _DescriptionCard extends StatelessWidget { final Service service; const _DescriptionCard({required this.service}); @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Description', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), const SizedBox(height: 10), Text(_description(service), style: const TextStyle(height: 1.45, color: Color(0xff5f6368)))]))); String _description(Service s) { switch (s.name) { case 'GitHub API': return "Service responsable de l'authentification et de l'intégration avec les dépôts de code."; case 'FreeOpenAPI': return 'Service de passerelle API pour les requêtes de données publiques ouvertes.'; case 'Cloudflare': return 'Réseau de diffusion de contenu (CDN) et protection contre les attaques distribuées.'; case 'Test HTTP 200': return 'Endpoint de référence pour valider la connectivité réseau et les réponses HTTP standard.'; case 'Test indisponible': return 'Endpoint simulant une panne de service (HTTP 503 Service Unavailable).'; default: return 'Service responsable du traitement des requêtes et de la gestion des opérations.'; } } }
class _HistoryCard extends StatelessWidget { final List<Service> history; final Service current; const _HistoryCard({required this.history, required this.current}); @override Widget build(BuildContext context) { final entries = history.isEmpty ? [current] : history; return Card(child: Padding(padding: const EdgeInsets.fromLTRB(16, 16, 16, 8), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Historique', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), const SizedBox(height: 8), ...entries.map((entry) => _HistoryRow(service: entry))]))); } }
class _HistoryRow extends StatelessWidget { final Service service; const _HistoryRow({required this.service}); @override Widget build(BuildContext context) { final color = service.status == ServiceStatus.operational ? const Color(0xff28a745) : service.status == ServiceStatus.degraded ? const Color(0xffff9800) : const Color(0xffdc3545); return Padding(padding: const EdgeInsets.symmetric(vertical: 8), child: Row(children: [Icon(service.status == ServiceStatus.operational ? Icons.check_circle : service.status == ServiceStatus.degraded ? Icons.warning_rounded : Icons.cancel, color: color, size: 20), const SizedBox(width: 10), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_time(service.lastChecked), style: const TextStyle(fontWeight: FontWeight.w600)), Text(_label(service.status), style: TextStyle(color: color, fontSize: 13, fontWeight: FontWeight.w600))])), Text(service.status == ServiceStatus.down ? '—' : '${service.responseTime} ms', style: const TextStyle(fontWeight: FontWeight.w600))])); } String _time(DateTime v) => '${v.day.toString().padLeft(2, '0')}/${v.month.toString().padLeft(2, '0')}, ${v.hour.toString().padLeft(2, '0')}:${v.minute.toString().padLeft(2, '0')}'; String _label(ServiceStatus s) => s == ServiceStatus.operational ? 'Opérationnel' : s == ServiceStatus.degraded ? 'Dégradé' : 'Indisponible'; }
